
// Generated by MyGeneration Version # (1.3.0.3)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class BlogPage : _BlogPage
	{
		public BlogPage()
		{
		
		}

        public virtual int LoadBlogsWithPaging(int pageIndex, int pageSize)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@PageIndex", SqlDbType.Int), pageIndex);
            parameters.Add(new SqlParameter("@PageSize", SqlDbType.Int), pageSize);
            SqlParameter spRecordCount = new SqlParameter("@RecordCount", SqlDbType.Int);
            spRecordCount.Direction = ParameterDirection.Output;
            parameters.Add(spRecordCount, 0);
            base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_BlogPage_LoadBlogsWithPaging]", parameters);
            return (int)spRecordCount.Value;
        }
	}
}
