
// Generated by MyGeneration Version # (1.3.0.3)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using VikkiSoft_BLL.DAL;

namespace VikkiSoft_BLL
{
	public class BlogPageCity : _BlogPageCity
	{
		public BlogPageCity()
		{
		
		}

        public virtual bool LoadByBlogPageID(int blogPageID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@BlogPageID", SqlDbType.Int), blogPageID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_BlogPageCity_LoadByBlogPageID]", parameters);
        }
	}
}
