
// Generated by MyGeneration Version # (1.3.0.3)

using System.Collections.Specialized;
using System.Data;
using System.Data.SqlClient;
using  VikkiSoft_BLL.DAL;

namespace  VikkiSoft_BLL
{
	public class Site : _Site
	{
		public Site()
		{
		
		}

        public virtual bool LoadWithSiteTypeName()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Site_LoadWithSiteTypeName]");
        }

        public virtual bool LoadBySiteTypeID(int siteTypeID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@SiteTypeID", SqlDbType.Int), siteTypeID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Site_LoadBySiteTypeID]", parameters);
        }

        public virtual bool LoadMainSite()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Site_LoadMainSite]");
        }

        public virtual bool LoadByCountryID(int countryID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@CountryID", SqlDbType.Int), countryID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Site_LoadByCountryID]", parameters);
        }

        public virtual bool LoadByCityID(int cityID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@CityID", SqlDbType.Int), cityID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Site_LoadByCityID]", parameters);
        }

        public virtual bool LoadByBlogPageID(int blogPageID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(new SqlParameter("@BlogPageID", SqlDbType.Int), blogPageID);

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Site_LoadByBlogPageID]", parameters);
        }

        public virtual bool LoadNeedChangeURL()
        {
            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "usp_Site_LoadNeedChangeURL]");
        }
	}
}
