
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace VikkiSoft_BLL.DAL
{
    public abstract class _CitySite : SqlClientEntity
    {
        public _CitySite()
        {
            this.QuerySource = "CitySite";
            this.MappingName = "CitySite";

        }

        //=================================================================
        //  public Overrides void AddNew()
        //=================================================================
        //
        //=================================================================
        public override void AddNew()
        {
            base.AddNew();

        }


        public override void FlushData()
        {
            this._whereClause = null;
            this._aggregateClause = null;
            base.FlushData();
        }

        //=================================================================
        //  	public Function LoadAll() As Boolean
        //=================================================================
        //  Loads all of the records in the database, and sets the currentRow to the first row
        //=================================================================
        public bool LoadAll()
        {
            ListDictionary parameters = null;

            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAllCitySite]", parameters);
        }

        //=================================================================
        // public Overridable Function LoadByPrimaryKey()  As Boolean
        //=================================================================
        //  Loads a single row of via the primary key
        //=================================================================
        public virtual bool LoadByPrimaryKey(int CitySiteID)
        {
            ListDictionary parameters = new ListDictionary();
            parameters.Add(Parameters.CitySiteID, CitySiteID);


            return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadCitySiteByPrimaryKey]", parameters);
        }

        #region Parameters
        protected class Parameters
        {

            public static SqlParameter CitySiteID
            {
                get
                {
                    return new SqlParameter("@CitySiteID", SqlDbType.Int, 0);
                }
            }

            public static SqlParameter CityID
            {
                get
                {
                    return new SqlParameter("@CityID", SqlDbType.Int, 0);
                }
            }

            public static SqlParameter SiteID
            {
                get
                {
                    return new SqlParameter("@SiteID", SqlDbType.Int, 0);
                }
            }
        }
        #endregion

        #region ColumnNames
        public class ColumnNames
        {
            public const string CitySiteID = "CitySiteID";
            public const string CityID = "CityID";
            public const string SiteID = "SiteID";

            static public string ToPropertyName(string columnName)
            {
                if (ht == null)
                {
                    ht = new Hashtable();

                    ht[CitySiteID] = _CitySite.PropertyNames.CitySiteID;
                    ht[CityID] = _CitySite.PropertyNames.CityID;
                    ht[SiteID] = _CitySite.PropertyNames.SiteID;

                }
                return (string)ht[columnName];
            }

            static private Hashtable ht = null;
        }
        #endregion

        #region PropertyNames
        public class PropertyNames
        {
            public const string CitySiteID = "CitySiteID";
            public const string CityID = "CityID";
            public const string SiteID = "SiteID";

            static public string ToColumnName(string propertyName)
            {
                if (ht == null)
                {
                    ht = new Hashtable();

                    ht[CitySiteID] = _CitySite.ColumnNames.CitySiteID;
                    ht[CityID] = _CitySite.ColumnNames.CityID;
                    ht[SiteID] = _CitySite.ColumnNames.SiteID;

                }
                return (string)ht[propertyName];
            }

            static private Hashtable ht = null;
        }
        #endregion

        #region StringPropertyNames
        public class StringPropertyNames
        {
            public const string CitySiteID = "s_CitySiteID";
            public const string CityID = "s_CityID";
            public const string SiteID = "s_SiteID";

        }
        #endregion

        #region Properties

        public virtual int CitySiteID
        {
            get
            {
                return base.Getint(ColumnNames.CitySiteID);
            }
            set
            {
                base.Setint(ColumnNames.CitySiteID, value);
            }
        }

        public virtual int CityID
        {
            get
            {
                return base.Getint(ColumnNames.CityID);
            }
            set
            {
                base.Setint(ColumnNames.CityID, value);
            }
        }

        public virtual int SiteID
        {
            get
            {
                return base.Getint(ColumnNames.SiteID);
            }
            set
            {
                base.Setint(ColumnNames.SiteID, value);
            }
        }

        #endregion

        #region String Properties

        public virtual string s_CitySiteID
        {
            get
            {
                return this.IsColumnNull(ColumnNames.CitySiteID) ? string.Empty : base.GetintAsString(ColumnNames.CitySiteID);
            }
            set
            {
                if (string.Empty == value)
                    this.SetColumnNull(ColumnNames.CitySiteID);
                else
                    this.CitySiteID = base.SetintAsString(ColumnNames.CitySiteID, value);
            }
        }

        public virtual string s_CityID
        {
            get
            {
                return this.IsColumnNull(ColumnNames.CityID) ? string.Empty : base.GetintAsString(ColumnNames.CityID);
            }
            set
            {
                if (string.Empty == value)
                    this.SetColumnNull(ColumnNames.CityID);
                else
                    this.CityID = base.SetintAsString(ColumnNames.CityID, value);
            }
        }

        public virtual string s_SiteID
        {
            get
            {
                return this.IsColumnNull(ColumnNames.SiteID) ? string.Empty : base.GetintAsString(ColumnNames.SiteID);
            }
            set
            {
                if (string.Empty == value)
                    this.SetColumnNull(ColumnNames.SiteID);
                else
                    this.SiteID = base.SetintAsString(ColumnNames.SiteID, value);
            }
        }

        #endregion

        #region Where Clause
        public class WhereClause
        {
            public WhereClause(BusinessEntity entity)
            {
                this._entity = entity;
            }

            public TearOffWhereParameter TearOff
            {
                get
                {
                    if (_tearOff == null)
                    {
                        _tearOff = new TearOffWhereParameter(this);
                    }

                    return _tearOff;
                }
            }

            #region WhereParameter TearOff's
            public class TearOffWhereParameter
            {
                public TearOffWhereParameter(WhereClause clause)
                {
                    this._clause = clause;
                }


                public WhereParameter CitySiteID
                {
                    get
                    {
                        WhereParameter where = new WhereParameter(ColumnNames.CitySiteID, Parameters.CitySiteID);
                        this._clause._entity.Query.AddWhereParameter(where);
                        return where;
                    }
                }

                public WhereParameter CityID
                {
                    get
                    {
                        WhereParameter where = new WhereParameter(ColumnNames.CityID, Parameters.CityID);
                        this._clause._entity.Query.AddWhereParameter(where);
                        return where;
                    }
                }

                public WhereParameter SiteID
                {
                    get
                    {
                        WhereParameter where = new WhereParameter(ColumnNames.SiteID, Parameters.SiteID);
                        this._clause._entity.Query.AddWhereParameter(where);
                        return where;
                    }
                }

                private WhereClause _clause;
            }
            #endregion

            public WhereParameter CitySiteID
            {
                get
                {
                    if (_CitySiteID_W == null)
                    {
                        _CitySiteID_W = TearOff.CitySiteID;
                    }
                    return _CitySiteID_W;
                }
            }

            public WhereParameter CityID
            {
                get
                {
                    if (_CityID_W == null)
                    {
                        _CityID_W = TearOff.CityID;
                    }
                    return _CityID_W;
                }
            }

            public WhereParameter SiteID
            {
                get
                {
                    if (_SiteID_W == null)
                    {
                        _SiteID_W = TearOff.SiteID;
                    }
                    return _SiteID_W;
                }
            }

            private WhereParameter _CitySiteID_W = null;
            private WhereParameter _CityID_W = null;
            private WhereParameter _SiteID_W = null;

            public void WhereClauseReset()
            {
                _CitySiteID_W = null;
                _CityID_W = null;
                _SiteID_W = null;

                this._entity.Query.FlushWhereParameters();

            }

            private BusinessEntity _entity;
            private TearOffWhereParameter _tearOff;

        }

        public WhereClause Where
        {
            get
            {
                if (_whereClause == null)
                {
                    _whereClause = new WhereClause(this);
                }

                return _whereClause;
            }
        }

        private WhereClause _whereClause = null;
        #endregion

        #region Aggregate Clause
        public class AggregateClause
        {
            public AggregateClause(BusinessEntity entity)
            {
                this._entity = entity;
            }

            public TearOffAggregateParameter TearOff
            {
                get
                {
                    if (_tearOff == null)
                    {
                        _tearOff = new TearOffAggregateParameter(this);
                    }

                    return _tearOff;
                }
            }

            #region AggregateParameter TearOff's
            public class TearOffAggregateParameter
            {
                public TearOffAggregateParameter(AggregateClause clause)
                {
                    this._clause = clause;
                }


                public AggregateParameter CitySiteID
                {
                    get
                    {
                        AggregateParameter aggregate = new AggregateParameter(ColumnNames.CitySiteID, Parameters.CitySiteID);
                        this._clause._entity.Query.AddAggregateParameter(aggregate);
                        return aggregate;
                    }
                }

                public AggregateParameter CityID
                {
                    get
                    {
                        AggregateParameter aggregate = new AggregateParameter(ColumnNames.CityID, Parameters.CityID);
                        this._clause._entity.Query.AddAggregateParameter(aggregate);
                        return aggregate;
                    }
                }

                public AggregateParameter SiteID
                {
                    get
                    {
                        AggregateParameter aggregate = new AggregateParameter(ColumnNames.SiteID, Parameters.SiteID);
                        this._clause._entity.Query.AddAggregateParameter(aggregate);
                        return aggregate;
                    }
                }

                private AggregateClause _clause;
            }
            #endregion

            public AggregateParameter CitySiteID
            {
                get
                {
                    if (_CitySiteID_W == null)
                    {
                        _CitySiteID_W = TearOff.CitySiteID;
                    }
                    return _CitySiteID_W;
                }
            }

            public AggregateParameter CityID
            {
                get
                {
                    if (_CityID_W == null)
                    {
                        _CityID_W = TearOff.CityID;
                    }
                    return _CityID_W;
                }
            }

            public AggregateParameter SiteID
            {
                get
                {
                    if (_SiteID_W == null)
                    {
                        _SiteID_W = TearOff.SiteID;
                    }
                    return _SiteID_W;
                }
            }

            private AggregateParameter _CitySiteID_W = null;
            private AggregateParameter _CityID_W = null;
            private AggregateParameter _SiteID_W = null;

            public void AggregateClauseReset()
            {
                _CitySiteID_W = null;
                _CityID_W = null;
                _SiteID_W = null;

                this._entity.Query.FlushAggregateParameters();

            }

            private BusinessEntity _entity;
            private TearOffAggregateParameter _tearOff;

        }

        public AggregateClause Aggregate
        {
            get
            {
                if (_aggregateClause == null)
                {
                    _aggregateClause = new AggregateClause(this);
                }

                return _aggregateClause;
            }
        }

        private AggregateClause _aggregateClause = null;
        #endregion

        protected override IDbCommand GetInsertCommand()
        {

            SqlCommand cmd = new SqlCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "[" + this.SchemaStoredProcedure + "InsertCitySite]";

            CreateParameters(cmd);

            SqlParameter p;
            p = cmd.Parameters[Parameters.CitySiteID.ParameterName];
            p.Direction = ParameterDirection.Output;

            return cmd;
        }

        protected override IDbCommand GetUpdateCommand()
        {

            SqlCommand cmd = new SqlCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "[" + this.SchemaStoredProcedure + "UpdateCitySite]";

            CreateParameters(cmd);

            return cmd;
        }

        protected override IDbCommand GetDeleteCommand()
        {

            SqlCommand cmd = new SqlCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "[" + this.SchemaStoredProcedure + "DeleteCitySite]";

            SqlParameter p;
            p = cmd.Parameters.Add(Parameters.CitySiteID);
            p.SourceColumn = ColumnNames.CitySiteID;
            p.SourceVersion = DataRowVersion.Current;


            return cmd;
        }

        private IDbCommand CreateParameters(SqlCommand cmd)
        {
            SqlParameter p;

            p = cmd.Parameters.Add(Parameters.CitySiteID);
            p.SourceColumn = ColumnNames.CitySiteID;
            p.SourceVersion = DataRowVersion.Current;

            p = cmd.Parameters.Add(Parameters.CityID);
            p.SourceColumn = ColumnNames.CityID;
            p.SourceVersion = DataRowVersion.Current;

            p = cmd.Parameters.Add(Parameters.SiteID);
            p.SourceColumn = ColumnNames.SiteID;
            p.SourceVersion = DataRowVersion.Current;

            return cmd;
        }
    }
}
