
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace VikkiSoft_BLL.DAL
{
	public abstract class _Settings : SqlClientEntity
	{
		public _Settings()
		{
			this.QuerySource = "Settings";
			this.MappingName = "Settings";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadAllSettings]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int SettingID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.SettingID, SettingID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "LoadSettingsByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter SettingID
			{
				get
				{
					return new SqlParameter("@SettingID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter UserName
			{
				get
				{
					return new SqlParameter("@UserName", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Password
			{
				get
				{
					return new SqlParameter("@Password", SqlDbType.VarChar, 50);
				}
			}
			
			public static SqlParameter Keywords
			{
				get
				{
					return new SqlParameter("@Keywords", SqlDbType.VarChar, 250);
				}
			}
		
			
			public static SqlParameter Title
			{
				get
				{
					return new SqlParameter("@Title", SqlDbType.VarChar, 100);
				}
			}
			
			public static SqlParameter Description
			{
				get
				{
					return new SqlParameter("@Description", SqlDbType.VarChar, 200);
				}
			}
			
			public static SqlParameter TitleSuffix
			{
				get
				{
					return new SqlParameter("@TitleSuffix", SqlDbType.VarChar, 100);
				}
			}

			public static SqlParameter Advert1
			{
				get
				{
					return new SqlParameter("@Advert1", SqlDbType.VarChar, 1000);
				}
			}

			public static SqlParameter Advert2
			{
				get
				{
					return new SqlParameter("@Advert2", SqlDbType.VarChar, 1000);
				}
			}

			public static SqlParameter Advert3
			{
				get
				{
					return new SqlParameter("@Advert3", SqlDbType.VarChar, 1000);
				}
			}
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string SettingID = "SettingID";
            public const string UserName = "UserName";
            public const string Password = "Password";
            public const string Keywords = "Keywords";
            public const string Title = "Title";
            public const string Description = "Description";
            public const string TitleSuffix = "TitleSuffix";
			public const string Advert1 = "Advert1";
			public const string Advert2 = "Advert2";
			public const string Advert3 = "Advert3";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SettingID] = _Settings.PropertyNames.SettingID;
					ht[UserName] = _Settings.PropertyNames.UserName;
					ht[Password] = _Settings.PropertyNames.Password;
					ht[Keywords] = _Settings.PropertyNames.Keywords;
					ht[Title] = _Settings.PropertyNames.Title;
					ht[Description] = _Settings.PropertyNames.Description;
					ht[TitleSuffix] = _Settings.PropertyNames.TitleSuffix;
					ht[Advert1] = _Settings.PropertyNames.Advert1;
					ht[Advert2] = _Settings.PropertyNames.Advert2;
					ht[Advert3] = _Settings.PropertyNames.Advert3;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string SettingID = "SettingID";
            public const string UserName = "UserName";
            public const string Password = "Password";
            public const string Keywords = "Keywords";
            public const string Title = "Title";
            public const string Description = "Description";
            public const string TitleSuffix = "TitleSuffix";
			public const string Advert1 = "Advert1";
			public const string Advert2 = "Advert2";
			public const string Advert3 = "Advert3";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[SettingID] = _Settings.ColumnNames.SettingID;
					ht[UserName] = _Settings.ColumnNames.UserName;
					ht[Password] = _Settings.ColumnNames.Password;
					ht[Keywords] = _Settings.ColumnNames.Keywords;
					ht[Title] = _Settings.ColumnNames.Title;
					ht[Description] = _Settings.ColumnNames.Description;
					ht[TitleSuffix] = _Settings.ColumnNames.TitleSuffix;
					ht[Advert1] = _Settings.ColumnNames.Advert1;
					ht[Advert2] = _Settings.ColumnNames.Advert2;
					ht[Advert3] = _Settings.ColumnNames.Advert3;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string SettingID = "s_SettingID";
            public const string UserName = "s_UserName";
            public const string Password = "s_Password";
            public const string Keywords = "s_Keywords";
            public const string Title = "s_Title";
            public const string Description = "s_Description";
            public const string TitleSuffix = "s_TitleSuffix";
			public const string Advert1 = "s_Advert1";
			public const string Advert2 = "s_Advert2";
			public const string Advert3 = "s_Advert3";
		}
		#endregion		
		
		#region Properties
	
		public virtual int SettingID
	    {
			get
	        {
				return base.Getint(ColumnNames.SettingID);
			}
			set
	        {
				base.Setint(ColumnNames.SettingID, value);
			}
		}

		public virtual string UserName
	    {
			get
	        {
				return base.Getstring(ColumnNames.UserName);
			}
			set
	        {
				base.Setstring(ColumnNames.UserName, value);
			}
		}

		public virtual string Password
	    {
			get
	        {
				return base.Getstring(ColumnNames.Password);
			}
			set
	        {
				base.Setstring(ColumnNames.Password, value);
			}
		}

		public virtual string Keywords
	    {
			get
	        {
				return base.Getstring(ColumnNames.Keywords);
			}
			set
	        {
				base.Setstring(ColumnNames.Keywords, value);
			}
		}

		public virtual string Title
	    {
			get
	        {
				return base.Getstring(ColumnNames.Title);
			}
			set
	        {
				base.Setstring(ColumnNames.Title, value);
			}
		}

		public virtual string Description
	    {
			get
	        {
				return base.Getstring(ColumnNames.Description);
			}
			set
	        {
				base.Setstring(ColumnNames.Description, value);
			}
		}

		public virtual string TitleSuffix
	    {
			get
	        {
				return base.Getstring(ColumnNames.TitleSuffix);
			}
			set
	        {
				base.Setstring(ColumnNames.TitleSuffix, value);
			}
		}

		public virtual string Advert1
		{
			get
			{
				return base.Getstring(ColumnNames.Advert1);
			}
			set
			{
				base.Setstring(ColumnNames.Advert1, value);
			}
		}

		public virtual string Advert2
		{
			get
			{
				return base.Getstring(ColumnNames.Advert2);
			}
			set
			{
				base.Setstring(ColumnNames.Advert2, value);
			}
		}

		public virtual string Advert3
		{
			get
			{
				return base.Getstring(ColumnNames.Advert3);
			}
			set
			{
				base.Setstring(ColumnNames.Advert3, value);
			}
		}

		#endregion

		#region String Properties

		public virtual string s_SettingID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.SettingID) ? string.Empty : base.GetintAsString(ColumnNames.SettingID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.SettingID);
				else
					this.SettingID = base.SetintAsString(ColumnNames.SettingID, value);
			}
		}

		public virtual string s_UserName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UserName) ? string.Empty : base.GetstringAsString(ColumnNames.UserName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UserName);
				else
					this.UserName = base.SetstringAsString(ColumnNames.UserName, value);
			}
		}

		public virtual string s_Password
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Password) ? string.Empty : base.GetstringAsString(ColumnNames.Password);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Password);
				else
					this.Password = base.SetstringAsString(ColumnNames.Password, value);
			}
		}

		public virtual string s_Keywords
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Keywords) ? string.Empty : base.GetstringAsString(ColumnNames.Keywords);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Keywords);
				else
					this.Keywords = base.SetstringAsString(ColumnNames.Keywords, value);
			}
		}

		public virtual string s_Title
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Title) ? string.Empty : base.GetstringAsString(ColumnNames.Title);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Title);
				else
					this.Title = base.SetstringAsString(ColumnNames.Title, value);
			}
		}

		public virtual string s_Description_
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Description) ? string.Empty : base.GetstringAsString(ColumnNames.Description);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Description);
				else
					this.Description = base.SetstringAsString(ColumnNames.Description, value);
			}
		}

		public virtual string s_TitleSuffix
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.TitleSuffix) ? string.Empty : base.GetstringAsString(ColumnNames.TitleSuffix);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.TitleSuffix);
				else
					this.TitleSuffix = base.SetstringAsString(ColumnNames.TitleSuffix, value);
			}
		}

		public virtual string s_Advert1
		{
			get
			{
				return this.IsColumnNull(ColumnNames.Advert1) ? string.Empty : base.GetstringAsString(ColumnNames.Advert1);
			}
			set
			{
				if (string.Empty == value)
					this.SetColumnNull(ColumnNames.Advert1);
				else
					this.Advert1 = base.SetstringAsString(ColumnNames.Advert1, value);
			}
		}

		public virtual string s_Advert2
		{
			get
			{
				return this.IsColumnNull(ColumnNames.Advert2) ? string.Empty : base.GetstringAsString(ColumnNames.Advert2);
			}
			set
			{
				if (string.Empty == value)
					this.SetColumnNull(ColumnNames.Advert2);
				else
					this.Advert2 = base.SetstringAsString(ColumnNames.Advert2, value);
			}
		}

		public virtual string s_Advert3
		{
			get
			{
				return this.IsColumnNull(ColumnNames.Advert3) ? string.Empty : base.GetstringAsString(ColumnNames.Advert3);
			}
			set
			{
				if (string.Empty == value)
					this.SetColumnNull(ColumnNames.Advert3);
				else
					this.Advert3 = base.SetstringAsString(ColumnNames.Advert3, value);
			}
		}

		#endregion

		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter SettingID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.SettingID, Parameters.SettingID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter UserName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UserName, Parameters.UserName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Password
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Password, Parameters.Password);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Keywords
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Keywords, Parameters.Keywords);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Title
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Title, Parameters.Title);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Description
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter TitleSuffix
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.TitleSuffix, Parameters.TitleSuffix);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Advert1
				{
					get
					{
						WhereParameter where = new WhereParameter(ColumnNames.Advert1, Parameters.Advert1);
						this._clause._entity.Query.AddWhereParameter(where);
						return where;
					}
				}

				public WhereParameter Advert2
				{
					get
					{
						WhereParameter where = new WhereParameter(ColumnNames.Advert2, Parameters.Advert2);
						this._clause._entity.Query.AddWhereParameter(where);
						return where;
					}
				}

				public WhereParameter Advert3
				{
					get
					{
						WhereParameter where = new WhereParameter(ColumnNames.Advert3, Parameters.Advert3);
						this._clause._entity.Query.AddWhereParameter(where);
						return where;
					}
				}

				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter SettingID
		    {
				get
		        {
					if(_SettingID_W == null)
	        	    {
						_SettingID_W = TearOff.SettingID;
					}
					return _SettingID_W;
				}
			}

			public WhereParameter UserName
		    {
				get
		        {
					if(_UserName_W == null)
	        	    {
						_UserName_W = TearOff.UserName;
					}
					return _UserName_W;
				}
			}

			public WhereParameter Password
		    {
				get
		        {
					if(_Password_W == null)
	        	    {
						_Password_W = TearOff.Password;
					}
					return _Password_W;
				}
			}

			public WhereParameter Keywords
		    {
				get
		        {
					if(_Keywords_W == null)
	        	    {
						_Keywords_W = TearOff.Keywords;
					}
					return _Keywords_W;
				}
			}

			public WhereParameter Title
		    {
				get
		        {
					if(_Title_W == null)
	        	    {
						_Title_W = TearOff.Title;
					}
					return _Title_W;
				}
			}

			public WhereParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public WhereParameter TitleSuffix
		    {
				get
		        {
					if(_TitleSuffix_W == null)
	        	    {
						_TitleSuffix_W = TearOff.TitleSuffix;
					}
					return _TitleSuffix_W;
				}
			}

			public WhereParameter Advert1
			{
				get
				{
					if (_Advert1_W == null)
					{
						_Advert1_W = TearOff.Advert1;
					}
					return _Advert1_W;
				}
			}

			public WhereParameter Advert2
			{
				get
				{
					if (_Advert2_W == null)
					{
						_Advert2_W = TearOff.Advert2;
					}
					return _Advert2_W;
				}
			}

			public WhereParameter Advert3
			{
				get
				{
					if (_Advert3_W == null)
					{
						_Advert3_W = TearOff.Advert3;
					}
					return _Advert3_W;
				}
			}

			private WhereParameter _SettingID_W = null;
			private WhereParameter _UserName_W = null;
			private WhereParameter _Password_W = null;
			private WhereParameter _Keywords_W = null;
			private WhereParameter _Title_W = null;
			private WhereParameter _Description_W = null;
			private WhereParameter _TitleSuffix_W = null;
			private WhereParameter _Advert1_W = null;
			private WhereParameter _Advert2_W = null;
			private WhereParameter _Advert3_W = null;

			public void WhereClauseReset()
			{
				_SettingID_W = null;
				_UserName_W = null;
				_Password_W = null;
				_Keywords_W = null;
				_Title_W = null;
				_Description_W = null;
				_TitleSuffix_W = null;
				_Advert1_W = null;
				_Advert2_W = null;
				_Advert3_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter SettingID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.SettingID, Parameters.SettingID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter UserName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UserName, Parameters.UserName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Password
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Password, Parameters.Password);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Keywords
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Keywords, Parameters.Keywords);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Title
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Title, Parameters.Title);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Description
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter TitleSuffix
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.TitleSuffix, Parameters.TitleSuffix);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Advert1
				{
					get
					{
						AggregateParameter aggregate = new AggregateParameter(ColumnNames.Advert1, Parameters.Advert1);
						this._clause._entity.Query.AddAggregateParameter(aggregate);
						return aggregate;
					}
				}

				public AggregateParameter Advert2
				{
					get
					{
						AggregateParameter aggregate = new AggregateParameter(ColumnNames.Advert2, Parameters.Advert2);
						this._clause._entity.Query.AddAggregateParameter(aggregate);
						return aggregate;
					}
				}

				public AggregateParameter Advert3
				{
					get
					{
						AggregateParameter aggregate = new AggregateParameter(ColumnNames.Advert3, Parameters.Advert3);
						this._clause._entity.Query.AddAggregateParameter(aggregate);
						return aggregate;
					}
				}

				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter SettingID
		    {
				get
		        {
					if(_SettingID_W == null)
	        	    {
						_SettingID_W = TearOff.SettingID;
					}
					return _SettingID_W;
				}
			}

			public AggregateParameter UserName
		    {
				get
		        {
					if(_UserName_W == null)
	        	    {
						_UserName_W = TearOff.UserName;
					}
					return _UserName_W;
				}
			}

			public AggregateParameter Password
		    {
				get
		        {
					if(_Password_W == null)
	        	    {
						_Password_W = TearOff.Password;
					}
					return _Password_W;
				}
			}

			public AggregateParameter Keywords
		    {
				get
		        {
					if(_Keywords_W == null)
	        	    {
						_Keywords_W = TearOff.Keywords;
					}
					return _Keywords_W;
				}
			}

			public AggregateParameter Title
		    {
				get
		        {
					if(_Title_W == null)
	        	    {
						_Title_W = TearOff.Title;
					}
					return _Title_W;
				}
			}

			public AggregateParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public AggregateParameter TitleSuffix
		    {
				get
		        {
					if(_TitleSuffix_W == null)
	        	    {
						_TitleSuffix_W = TearOff.TitleSuffix;
					}
					return _TitleSuffix_W;
				}
			}

			public AggregateParameter Advert1
			{
				get
				{
					if (_Advert1_W == null)
					{
						_Advert1_W = TearOff.Advert1;
					}
					return _Advert1_W;
				}
			}

			public AggregateParameter Advert2
			{
				get
				{
					if (_Advert2_W == null)
					{
						_Advert2_W = TearOff.Advert2;
					}
					return _Advert2_W;
				}
			}

			public AggregateParameter Advert3
			{
				get
				{
					if (_Advert3_W == null)
					{
						_Advert3_W = TearOff.Advert3;
					}
					return _Advert3_W;
				}
			}

			private AggregateParameter _SettingID_W = null;
			private AggregateParameter _UserName_W = null;
			private AggregateParameter _Password_W = null;
			private AggregateParameter _Keywords_W = null;
			private AggregateParameter _Title_W = null;
			private AggregateParameter _Description_W = null;
			private AggregateParameter _TitleSuffix_W = null;
			private AggregateParameter _Advert1_W = null;
			private AggregateParameter _Advert2_W = null;
			private AggregateParameter _Advert3_W = null;

			public void AggregateClauseReset()
			{
				_SettingID_W = null;
				_UserName_W = null;
				_Password_W = null;
				_Keywords_W = null;
				_Title_W = null;
				_Description_W = null;
				_TitleSuffix_W = null;
				_Advert1_W = null;
				_Advert2_W = null;
				_Advert3_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "InsertSettings]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.SettingID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "UpdateSettings]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "DeleteSettings]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.SettingID);
			p.SourceColumn = ColumnNames.SettingID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.SettingID);
			p.SourceColumn = ColumnNames.SettingID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.UserName);
			p.SourceColumn = ColumnNames.UserName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Password);
			p.SourceColumn = ColumnNames.Password;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Keywords);
			p.SourceColumn = ColumnNames.Keywords;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Title);
			p.SourceColumn = ColumnNames.Title;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Description);
			p.SourceColumn = ColumnNames.Description;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.TitleSuffix);
			p.SourceColumn = ColumnNames.TitleSuffix;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Advert1);
			p.SourceColumn = ColumnNames.Advert1;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Advert2);
			p.SourceColumn = ColumnNames.Advert2;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Advert3);
			p.SourceColumn = ColumnNames.Advert3;
			p.SourceVersion = DataRowVersion.Current;

			return cmd;
		}
	}
}
