DECLARE @UpdatedDate DateTime
SET @UpdatedDate=DATEADD(yy,-10,GETUTCDATE())
SELECT company_id AS DId, CONVERT(nvarchar,Id) AS TicketKey, Id, ISNULL(KB,0) AS IsKB, ISNULL(TicketNumberPrefix,'') + CONVERT(nvarchar,TicketNumber) AS TicketNumber, Subject, NextStep, KBSearchDesc, Workpad, Note, ReqCompNote, FollowUpNote, ClosureNote, vchConfirmedNote AS ConfirmedNote,
(SELECT MAX(v) FROM (VALUES (t.CreateTime), (t.UpdatedTime), ((SELECT MAX(dtDate) FROM TicketLogs tl WHERE tl.DId=t.company_id AND tl.TId=t.Id)), ((SELECT MAX(ISNULL(UpdatedTime, CreatedTime)) FROM TicketTime tt WHERE tt.DepartmentId=t.company_id AND tt.TicketId=t.Id)), ((SELECT MAX(ISNULL(UpdatedAt, CreatedAt)) FROM ToDoItem tdi WHERE tdi.DId=t.company_id AND tdi.TicketId=t.Id))) AS value(v)) AS TicketUpdatedDate,
(SELECT STUFF((SELECT '| ' + TTX.ValCol FROM (SELECT m.v.value('.', 'nvarchar(100)') AS ValCol FROM (SELECT CAST(CustomXML AS XML) AS XmlCol FROM tbl_ticket WHERE company_id=t.company_id and Id=t.Id) TX CROSS APPLY XmlCol.nodes('/root/field/value')m(v)) TTX FOR XML PATH('')),1,1,'')) AS CustomFieldValues,
(SELECT STUFF((SELECT '| ' + vchNote FROM TicketLogs tl WHERE tl.DId = t.company_id AND tl.TId=t.Id AND (tl.vchType='Initial Post' OR tl.vchType='Response' OR tl.vchType='Closed' OR tl.vchType='Transfer' OR tl.vchType='On Hold' OR tl.vchType='ReOpened' OR tl.vchType='Waiting on Response' OR tl.vchType='Escalation' OR tl.vchType='Descalation' OR tl.vchType='Remote Assistance')  FOR XML PATH('')),1,1,'')) AS TicketLogNotes,
(SELECT STUFF((SELECT '| ' + Note FROM TicketMiscCosts tmc WHERE tmc.DId = t.company_id AND tmc.TicketId=t.Id FOR XML PATH('')),1,1,'')) AS TicketMiscCostNotes,
(SELECT STUFF((SELECT '| ' + Note FROM TicketTravelCosts ttc WHERE ttc.DepartmentId = t.company_id AND ttc.TicketId=t.Id FOR XML PATH('')),1,1,'')) AS TicketTravelCostNotes,
(SELECT STUFF((SELECT '| ' + Note FROM TicketTime tt WHERE tt.DepartmentId = t.company_id AND tt.TicketId=t.Id FOR XML PATH('')),1,1,'')) AS TicketTimeNotes,
(SELECT STUFF((SELECT '| ' + Title FROM ToDoItem tdi WHERE tdi.DId = t.company_id AND tdi.TicketId=t.Id FOR XML PATH('')),1,1,'')) AS TicketToDoTitles,
(SELECT STUFF((SELECT '| ' + Text FROM ToDoItem tdi WHERE tdi.DId = t.company_id AND tdi.TicketId=t.Id FOR XML PATH('')),1,1,'')) AS TicketToDoTexts
FROM tbl_ticket t 
WHERE t.CreateTime BETWEEN @UpdatedDate AND GETUTCDATE() OR t.UpdatedTime BETWEEN @UpdatedDate AND GETUTCDATE() OR (SELECT MAX(dtDate) FROM TicketLogs tl WHERE tl.DId=t.company_id AND tl.TId=t.Id) BETWEEN @UpdatedDate AND GETUTCDATE() OR (SELECT MAX(ISNULL(UpdatedTime, CreatedTime)) FROM TicketTime tt WHERE tt.DepartmentId=t.company_id AND tt.TicketId=t.Id) BETWEEN @UpdatedDate AND GETUTCDATE() OR (SELECT MAX(ISNULL(UpdatedAt, CreatedAt)) FROM ToDoItem tdi WHERE tdi.DId=t.company_id AND tdi.TicketId=t.Id) BETWEEN @UpdatedDate AND GETUTCDATE()
order by t.Id
